### ISSUE TITLE
Faulty Regex in valid_pin

### ISSUE THREAD

**Issue by zkldi** [DragonMinded/bemaniutils#24]
https://github.com/DragonMinded/bemaniutils/blob/33d0000c771b6da22e45327921d1af21d9f83c81/bemani/frontend/app.py#L225-L231

Should probably be `^\d\d\d\d$` (or better, `^\d{4}$`) and similar for the bottom, as this currently matches anything containing 4 sequential digits.

Opening as an issue instead of a PR as this might be intentional.

**Comment by DragonMinded** [comment]
The regex was meant to be complete, not partial. So the correct fix would be to either switch to `fullmatch` or one of the proposed regexes in this issue.
