### ISSUE TITLE
Unrecognized service eventlog method write

### ISSUE THREAD

**Issue by stepmaniatic** [DragonMinded/bemaniutils#26]
Hello. Trying to make it work, got this error when try to create a new pin/card in game:

![Captura](https://user-images.githubusercontent.com/87998709/127038083-3502a641-b0cf-4138-9b1d-e34087227ad3.PNG)

I have no idea of how to fix it.

![0Captura](https://user-images.githubusercontent.com/87998709/127037810-7c4e8f4e-5b03-4739-9687-d3e94d939b98.PNG)

**Comment by camprevail** [comment]
DDR A20 isn't supported

**Comment by stepmaniatic** [comment]
> DDR A20 isn't supported

omg you're right... thanks
