### ISSUE TITLE
Struct util shadows standard library

### ISSUE THREAD

**Issue by tumes** [DragonMinded/bemaniutils#4]
Hey there. First I just wanted to say thank you for all your hard work, this is an absolutely incredible tool and I have had a blast playing with it!

On to my issue: I spun this up on my mac with zero issue on my first pass. When I attempted to get it running on a pi for my second try, I used the stock latest raspbian release and it blew up because of the struct util colliding with the standard library when I tried to run the services script in that context. Now granted, I'm a ruby person and you could fit what I know about python dev into half a thimble but from my (very limited) understanding, it seems like the typical best practice is to avoid shadowing the standard library if possible?

I blasted the file away to get it running locally, but I was wondering if you'd be amenable to a PR that renames the util to avoid the collision. Feel free to disregard if this is just my flagrant ignorance standard python practice showing, but I have the code prepped if you're willing to field it.

**Comment by DragonMinded** [comment]
What do you mean by struct util? I'm not entirely sure what the issue you're having is. Everything should be namespaced inside the bemani package so there shouldn't be a possibility of shadowing.

**Comment by tumes** [comment]
My apologies for being unclear, I meant this file:

https://github.com/DragonMinded/bemaniutils/blob/master/bemani/utils/struct.py

In that specific environment (latest raspbian), when I ran the services script, waaaaay down the chain pickle was complaining because it was trying to import `pack` and `unpack` from `struct` and was attempting to do so from the file above instead of the standard library.

**Comment by DragonMinded** [comment]
That shouldn't be possible, unless you are running things directly out of the bemani/ directory using a shell command? Everything is namespaced to the bemani package, so that file is "bemani.utils.struct" and can't shadow "struct" under any possibility. Do you have stack traces?

**Comment by tumes** [comment]
Sure thing, here ya go:

```
pi@eamuse:~/bemaniutils $ ./services --port 5730 --config config/server.yaml 
 * Serving Flask app "services" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5730/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/pi/bemaniutils/bemani/utils/services.py", line 6, in <module>
    from flask import Flask, request, redirect, Response, make_response
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 16, in <module>
    from jinja2._compat import text_type, string_types, implements_iterator, \
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 31, in <module>
    import pickle
  File "/usr/lib/python3.7/pickle.py", line 33, in <module>
    from struct import pack, unpack
ImportError: cannot import name 'pack' from 'struct' (/home/pi/bemaniutils/bemani/utils/struct.py)
```

**Comment by tumes** [comment]
Feel free to disregard all of this though, it is totally usable if I just delete or rename that file, not a huge deal. Plus I only barely know what I'm doing and may have just set up the environment poorly. I was more thinking about smoothing out bumps for other folks, no worries if this is not worth your time.

**Comment by DragonMinded** [comment]
I'm not sure its a general issue, otherwise it would show up on everyone's import (including on your mac and on my setup). I suspect there might be some weird virtual env stuff going on. What version of python is running on the RPI? Also, the scripts were modified a LONG time ago by somebody else trying to get things running on a mac. https://github.com/DragonMinded/bemaniutils/blob/master/services#L4 in particular should be running which forces python to see the bemani package. However, the above line grabs the current working directory *instead* of the script directory which was the original intent. I never changed it back, but a limitation is that the scripts *must* be run from the `bemani/` directory, not `bemani/utils/`. Perhaps its a starting directory problem?

I don't think its worth closing this, just in case somebody else DOES run into it.

**Comment by tumes** [comment]
I believe it's 3.7.3 on the image I grabbed... Last Friday? Something like that.

Yeah, that sounds like that might be the issue? Or something similar. To be honest I eventually stubbed out that python path reference with a string since the last thing I did was set up a systemd unit to launch all the stuff on boot, but that's a whole other kettle of fish.

Anyway, thanks again, I really appreciate your work on these tools!

**Comment by DragonMinded** [comment]
No problem. I'm taking a stab at fixing the scripts themselves using `runpy.run_module` which seems to work and should allow execution of them from anywhere. If you've installed the bemani package into a virtual environment using setuptools, you would want to change the scripts to something like the following:

```
source /path/to/virtualenv/bin/activate
python3 -m bemani.utils.services "$@"
```

If you installed to the system python, you can skip all that and just run `python3 -m bemani.utils.services` in place of `services` script. However, as they aren't meant to be run standalone in a production environment, the README details how to stand up nginx/uwsgi to serve things properly. The above script modifications would relate to things like `scheduler` or other maintenance scripts like `dbutils` that you want to run periodically.

**Comment by DragonMinded** [comment]
You probably found https://github.com/DragonMinded/bemaniutils/tree/master/examples but if not, that has examples for how to set things up.

**Comment by DragonMinded** [comment]
I pushed some new changes that update how the scripts get called. If you get a moment can you double check that they still work on Mac, and see if it doesn't fix the issue on your RPI?

**Comment by tumes** [comment]
Works beautifully on my Mac _and_ my RPI both run from the bemaniutils folder _and_ as a systemd unit that loads on boot. Thank you so much!
