### ISSUE TITLE
Normal and Hard mode scores are not currently stored separately for jubeat

### ISSUE THREAD

**Issue by Subject38** [DragonMinded/bemaniutils#5]
I'm working on getting jubeat festo support in this server and have had quite the ride learning how this server works and I was curious as to how I should approach storing hard mode scores. I was thinking to just create a new table for hard mode scores and when a given song only has a score in hard mode i make a blank entry in the normal mode score table so that I only need to iterate once through the table and check both tables for a score. I would prefer not to make a second table but since all the scores are currently uniquely stored in the table I couldn't think of any other reasonable approach

**Comment by DragonMinded** [comment]
Are hard mode scores newly introduced in Jubeat? I don't remember there being any separation of scores except by song/chart. Your proposed method is a bit hacky, there's a reason why there isn't any game-specific tables in the server. Do you have a reference or a quick description for hard mode versus normal mode in Festo?

**Comment by Subject38** [comment]
When the game sends back a score, there is now an is_hard_mode variable sent back and when the server sends the scores to the game there is now two blocks sent per song id, one for hard mode and one for normal. I'm not sure if this is done before festo because I didn't look too much into clan. Example of how they are separated. The left one would not be accepted by jubeat festo ![unknown-24.png](https://user-images.githubusercontent.com/11450329/87106952-2e52a200-c224-11ea-8cb8-c8db0db2e782.png)

**Comment by DragonMinded** [comment]
Remywiki links to https://twitter.com/jubeat_staff/status/1017392642030571521 which says that yes, this was added for festo. In order for front-end support to kinda "drop in" for hard mode charts, you will definitely want to support these in a more standard way. I can't think of any other games that store separate scores for normal and hard mode except for maybe oooold Pop'n (even IIDX just stores the clear lamp achieved on the hardest mode, while keeping the scores identical).

This network software purposefully keeps a separation between in-game song/chart and its own concept of song/chart. This has made it easy to link songs through ID renames (thanks DDR), revivals (thanks IIDX) and even shuffling around chart ID (thanks Pop'n). You can see this most clearly in Pop'n 19 where they added Cho mode which adds cools. I linked those charts to the standard easy/normal/hard/ex charts in newer Pop'n games so the scores can be forwards compatible. I think the solution is to do a similar thing here. Let's define a new set of charts for hard mode easy, normal and ex, add those charts as well as the normal charts in read.py (they will be duplicates with different chart IDs which is fine), and then in the festo backend we can convert from game song/chart to the correct backend song/chart by looking at the is_hard_mode variable. You'll need to make sure that older versions of games filter out those scores and don't send them back to clients.

We can ignore displaying hard mode scores on the front end for starters until we figure out if we want them there, and if so, how to display them.

**Comment by Subject38** [comment]
I finally got around to working on it again and followed your advice and got it working. I need to get it implemented in webui but thank you so much for your input, it was super helpful.
