### ISSUE TITLE
Refactor older IIDX game classes to use the newer routing

### ISSUE THREAD

**Issue by Subject38** [DragonMinded/bemaniutils#50]
IIDX 20-23 all use the older routing style where the method name is extracted by the game class rather than having the method in the function name. I was going to start working on a different refactor only to realize this issue existed. I'll be opening a pull request later tonight hopefully to get this done. This issue is just for tracking purposes

**Comment by Subject38** [comment]
Not sure whether it's worth opening a separate issue for the other thing I wanted so I'll bring it up here. The pull request will also use the game_to_db_chart and db_to_game_chart abstraction that ddr uses since IIDX renumbers charts in IIDX 27 and later. After the basic refactoring is done, I'll submit a few pull requests for IIDX 27 and 28.

**Comment by DragonMinded** [comment]
I've been on-and-off again trying to get myself to go back to the legacy stuff and kill it for good, there should only be one routing method and the `handle_<service>_<method>` style makes a lot more sense than the legacy crap. I forget, what else is still using that? I think I got Pop'n updated last year when I did all the improvements to it.

For the game<-->db chart stuff, do you mean on the frontend? Because for the backend, the primed music DB + read should handle it.

**Comment by Subject38** [comment]
I mean in the backend. I need a function like:
```py
    def game_to_db_chart(self, db_chart: int) -> int:
        return {
            self.GAME_CHART_TYPE_B7: self.CHART_TYPE_B7,
            self.GAME_CHART_TYPE_N7: self.CHART_TYPE_N7,
            self.GAME_CHART_TYPE_H7: self.CHART_TYPE_H7,
            self.GAME_CHART_TYPE_A7: self.CHART_TYPE_A7,
            self.GAME_CHART_TYPE_L7: self.CHART_TYPE_L7,
            self.GAME_CHART_TYPE_B14: self.CHART_TYPE_B14,
            self.GAME_CHART_TYPE_N14: self.CHART_TYPE_N14,
            self.GAME_CHART_TYPE_H14: self.CHART_TYPE_H14,
            self.GAME_CHART_TYPE_A14: self.CHART_TYPE_A14,
            self.GAME_CHART_TYPE_L14: self.CHART_TYPE_L14,
        }[db_chart]
```
Because the game chart numbers changed between iidx 26 to iidx 27. I would like to add this same method to iidx 20-26 for the sake of code consistency even though a method like that would essentially do nothing.

**Comment by DragonMinded** [comment]
Hmmm, why can't that be handled by read.py? I forget why I did that indirection for DDR, but the idea of read.py and the music DB indirection is that the song can be identified by game + version + songid + chart from the perspective of the game, but still map to the correct music DB entry to link the score between versions. Let me look at DDR and figure out why I did that.

**Comment by DragonMinded** [comment]
I cannot for the life of me remember why I had the indirection for DDR when the indirection was supposed to be in the music DB, but also I could see how keeping a consistent set of charts would make both read.py and the frontend easier to implement, so I don't think I care either way. If that abstraction makes it easier to support newer IIDX, then go for it!
