### ISSUE TITLE
Make Dispatch logging configurable for services

### ISSUE THREAD

**Issue by Subject38** [DragonMinded/bemaniutils#62]
Should just need to change this line to something that references the configuration and add to the example config
https://github.com/DragonMinded/bemaniutils/blob/d6cddebe884324ad89204257278fc83ceb7b3487/bemani/utils/services.py#L58
Probably add an override for users running the server in dev/debug mode

**Comment by DragonMinded** [comment]
Fixed with f11fa7de1d5c207295907102f935b037ef1f3fad.
