### ISSUE TITLE
(afputils) Any chance of adding MGA support?

### ISSUE THREAD

**Issue by Zoft123** [DragonMinded/bemaniutils#70]
Been trying to look around to see if any there are any resources/tools/information in regards to extract the various graphics types used in Metal Gear Arcade until the AFP file format but have yielded 0 results thus far. The game doesn't have any IFS files included with it and instead includes solely an 'AFP' folder which contains both various **.afp** and **.xml** files. I will upload the folder here for anyone interested in looking into it. 

Example of the errors seen when trying to 'print' these AFP files. `raise Exception("Invalid bits set in feature mask!")
Exception: Invalid bits set in feature mask!
` also when trying to use the list option it leads to no output.

https://drive.google.com/file/d/1U8jymes0f0hdHElsfdX3ICvZSTWafXuB/view

**Comment by DragonMinded** [comment]
I had a look and it appears the game doesn't even care about the flag bit that is set on all the files. Possibly it is a version incompatibility flag. I pushed an update to ignore it and I can dump out the bytecode and textures of all the MGA files now. However, it looks like the game was coded similarly to BishiBashi, where the AFPs are not just movies but actual interactive flash files. My bytecode engine does not have support for the majority of what it needs to render nor does it have a place to run interactivity so there's likely not much you can render out of the animations. However, textures and such are available and should even be re-packable.

**Comment by Zoft123** [comment]
You are amazing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DragonMinded** [comment]
Note that the XML files are simply binxml properties, presumably used by various AFP files. You can decode them using `binutils` but they don't yield much interesting info aside from configuration data.

**Comment by DragonMinded** [comment]
Closing this as I don't think there's going to be much more development on MGA. If you find a bug in texture decoding/encoding feel free to open a new bug.
