### ISSUE TITLE
DDR X2 network not working

### ISSUE THREAD

**Issue by makoflagkk** [DragonMinded/bemaniutils#84]
![20231213_0](https://github.com/DragonMinded/bemaniutils/assets/130417801/395b8610-e47b-45c4-a9a5-da8a3a784376)

**Comment by Subject38** [comment]
Can you post logs or more information? This is a pretty generic error. In the server log do you see anything trying to connect? Do other games work?

**Comment by makoflagkk** [comment]
[log.txt](https://github.com/DragonMinded/bemaniutils/files/13667745/log.txt)

**Comment by makoflagkk** [comment]
![Screenshot 2023-12-13 215150](https://github.com/DragonMinded/bemaniutils/assets/130417801/1667965d-f32e-4a10-a340-bdf809ff5441)

**Comment by jorpz** [comment]
Did you change the service url? Your log suggests that you didn't change that. "unknown host"

**Comment by DragonMinded** [comment]
No, the logs clearly show them using the konami.fun address. This repo's issues are not for seeking help setting up individual games for operation on a network. It presumes that you have enough knowledge that you can successfully set games up before pointing at an instance of this.
